version: '2'
services:
    mobelhaus-app:
        image: mobelhaus
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mobelhaus-postgresql:5432/mobelhaus
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mobelhaus-postgresql:
        extends:
            file: postgresql.yml
            service: mobelhaus-postgresql
